language: r
sudo: required

r_check_args: --as-cran 

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-6
 - sudo apt-get install -qq gfortran-6
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6  90
 - sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-6  90 
 - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 90
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

cache: packages

addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

r_github_packages:
- kkholst/lava@fixNR
- tagteam/riskRegression

after_success:
  - Rscript -e 'library("covr");codecov(type="all")'


