language: r
r:
 - release 
 - devel
sudo: required
r_check_args: --as-cran 

## install x11
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

r_packages:
  - devtools
  
r_github_packages:
- tagteam/riskRegression

after_success:
  - Rscript -e 'library("covr");codecov(type="all")'


