#+BEGIN_HTML
<a href="http://cran.rstudio.com/web/packages/lavaSearch2/index.html"><img src="https://www.r-pkg.org/badges/version-last-release/lavaSearch2", alt="CRAN version"></a>
<a href="http://cranlogs.r-pkg.org/downloads/total/last-month/lavaSearch2"><img src="https://cranlogs.r-pkg.org/badges/lavaSearch2", alt="Download count"></a>
<a href="https://ci.appveyor.com/project/bozenne/lavaSearch2"><img src="https://ci.appveyor.com/api/projects/status/github/bozenne/lavaSearch2?svg=true" alt="Build status"></a>
<a href="https://github.com/bozenne/lavaSearch2/actions"><img src="https://github.com/bozenne/lavaSearch2/workflows/r/badge.svg" alt="Build status"></a>
<a href="http://www.gnu.org/licenses/gpl-3.0.html"><img src="https://img.shields.io/badge/License-GPLv3-blue.svg" alt="License"></a>
#+END_HTML

* lavaSeach2

*lavaSearch2* is a package for the R software
(https://www.r-project.org/) containing diagnostic and inference tools
for Latent Variable Models (LVM) estimated by maximum likelihood
(ML). It is built upon the *lava* package (see
[[https://github.com/kkholst/lava]]): the *lava* package is used to define
and estimate LVM. While *lava* can also be used to perform diagnostics
and inference, *lavaSearch2* improves some of the existing tools
in *lava*:
- Better control of the type 1 error rate when performing inference
  with small samples. The new methods =summary2= and =compare2=
  replace the =summary= and =compare= functions that performs,
  respectively, univariate and multivariate Wald tests. The new
  methods are also applicable to specific =gls= and =lme= models
  (*nlme* package).
- Better control of the type 1 error rate when adjusting for multiple
  comparisons with small samples (via the *multcomp*
  package). Compared to =glht=, the function =glht2= propagates small
  sample corrections to *multcomp*.
- Better detection of local dependencies that are not included in the
  LVM. The new method =modelsearch2= improves the =modelsearch= method
  by providing p-values adjusted for multiple comparisons. 

_Limitations_: *lavaSearch2* has been design for Gaussian linear
latent variable models. This means that it may not work / give valid
results:
- in presence of censored or binary outcomes.
- with stratified models (i.e. object of class =multigroup=).

* Installation of lavaSearch2
You can download and install the latest released version of the
software (CRAN version) using:
#+BEGIN_SRC R :exports both :eval never
install.packages("lavaSearch2")
#+END_SRC

For getting the most recent developments (if any!), you can download
and install the latest stable version of the software (Github version)
using:
#+BEGIN_SRC R :exports both :eval never
devtools::install_github("bozenne/lavaSearch2")
#+END_SRC


* Functionalities

See the vignette "Overview of the functionalities of the package
lavaSearch2" in [[./vignettes/overview.pdf]]

